#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib


sqlplus64 "s53chowd/09172572@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle12c.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl12c)))" <<EOF

SELECT E.EMPLOYEEID, E.EMPNAME
FROM EMPLOYEE E
WHERE NOT EXISTS (
    SELECT 1 FROM BOOKING B WHERE E.EMPLOYEEID = B.EMPLOYEEID
    )
UNION
SELECT E.EMPLOYEEID, E.EMPNAME
FROM EMPLOYEE E
WHERE EXISTS (SELECT 1 FROM BOOKING B WHERE B.EMPLOYEEID = E.EMPLOYEEID)
    AND EXISTS (SELECT 1 FROM BOOKING B WHERE B.EMPLOYEEID = E.EMPLOYEEID
                    AND B.TOTALPRICE < 300);



exit;

EOF
